apiVersion: v1
kind: Service
metadata:
  name: fastapi-loadbalancer-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: fastapi
  ports:
    - name: http
      port: 3000 # Service Port
      targetPort: 3000 # Container Port
    - name: python
      port: 8001 # Service Port
      targetPort: 8001 # Container Port
    - name: fastapi
      port: 8000 # Service Port
      targetPort: 8000 # Container Port
